### ISSUE TITLE
Translations are not used

### ISSUE THREAD

**Issue by Semir1212** [humhub/questions#27]
HH 1.16.2
Q&A 1.0.6

Should be German in this case:

![image](https://github.com/user-attachments/assets/06f0c06a-a3b4-4e2a-9bb9-2e551655efba)

**Comment by luke-** [comment]
@yurabakhtin Maybe we should release a new version including the messages or is this another prob?

**Comment by yurabakhtin** [comment]
@luke- Please try to relased version 1.0,7 because there I see the translations for the buttons:

![qa](https://github.com/user-attachments/assets/6dff1d69-2537-489f-9316-c706784107d2)

it was added only here https://github.com/humhub/questions/commit/20495ee132f5fe08531262b15b30e02d8260cb33

**Comment by luke-** [comment]
@yurabakhtin Thanks

Just released 1.0.7
