### ISSUE TITLE
Internal server error during uninstall/deactivate

### ISSUE THREAD

**Issue by Semir1212** [humhub/questions#6]
yii\base\UnknownMethodException: Calling unknown method: humhub\modules\questions\models\QuestionAnswer::hardDelete() in /var/www/intranet/htdocs/protected/vendor/yiisoft/yii2/base/Component.php:300
Stack trace:
#0 /var/www/intranet/htdocs/protected/modules/questions/models/Question.php(121): yii\base\Component->__call()
#1 /var/www/intranet/htdocs/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(754): humhub\modules\questions\models\Question->beforeDelete()
#2 /var/www/intranet/htdocs/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(724): yii\db\ActiveRecord->deleteInternal()
#3 /var/www/intranet/htdocs/protected/humhub/modules/content/components/ContentActiveRecord.php(558): yii\db\ActiveRecord->delete()
#4 /var/www/intranet/htdocs/protected/modules/questions/Module.php(108): humhub\modules\content\components\ContentActiveRecord->hardDelete()
#5 /var/www/intranet/htdocs/protected/modules/questions/Module.php(91): humhub\modules\questions\Module->deleteRecords()
#6 /var/www/intranet/htdocs/protected/humhub/components/ModuleManager.php(468): humhub\modules\questions\Module->disable()
#7 /var/www/intranet/htdocs/protected/humhub/modules/admin/controllers/ModuleController.php(154): humhub\components\ModuleManager->removeModule()
#8 [internal function]: humhub\modules\admin\controllers\ModuleController->actionRemove()
#9 /var/www/intranet/htdocs/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#10 /var/www/intranet/htdocs/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#11 /var/www/intranet/htdocs/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#12 /var/www/intranet/htdocs/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#13 /var/www/intranet/htdocs/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#14 /var/www/intranet/htdocs/index.php(25): yii\base\Application->run()
#15 {main}

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/questions/pull/9.
